### PR TITLE
Added GH Actions

### PR DESCRIPTION
**Pull request by tudny**
Added Rust code checks for PRs
Added Rust automatic code formatting

### CODE REVIEW

**Comment by mgr0dzicki** [comment]
obraz
what about this?

**Comment by tudny** [comment]
> 

Don't worry

**Comment by tudny** [comment]
@mgr0dzicki we need to remember to remove this temporary `#![allow(dead_code)]`

Related issue:
https://github.com/mimuw-jnp2-rust/project-matrix-busters/issues/5

**Review by mgr0dzicki — APPROVED** [review]
jest giit

**Pull request merged**
