### PR TITLE
Add inverse

### PR DESCRIPTION
**Pull request by mgr0dzicki**
todo: inverse is not implemented for scalars, but...
@tudny what do you think about not displaying echelon and inverse buttons for scalars?

### CODE REVIEW

**Review by tudny — APPROVED** [review]
LGTM!

**Comment by tudny** [comment]
@mgr0dzicki you can merge it

**Comment by mgr0dzicki** [comment]
> @mgr0dzicki you can merge it

hey and what about removing the buttons?

**Comment by tudny** [comment]
> todo: inverse is not implemented for scalars, but... @tudny what do you think about not displaying echelon and inverse buttons for scalars?

It depends on how much time is needed to remove them for scalars compared to adding those operations to scalars.

EDIT: As inverse makes sens for scalars, I think we should keep `inverse` button and get rid of `echelon`

**Comment by mgr0dzicki** [comment]
> EDIT: As inverse makes sens for scalars, I think we should keep `inverse` button and get rid of `echelon`

no dobra

**Review by tudny — APPROVED** [review]
lgbt

**Pull request merged**
