### PR TITLE
GUI

### PR DESCRIPTION
**Pull request by tudny**

### CODE REVIEW

**Comment by tudny** [comment]
@mgr0dzicki
I started the EGUI. Satisfied?

**Comment by tudny** [comment]
Implementation for Issue #7

**Comment by mgr0dzicki** [comment]
> @mgr0dzicki I started the EGUI. Satisfied?

Don't be mad at me :(( Really appreciate, it's beautiful! :heart:

**Comment by tudny** [comment]
This PR was mainly developed during a two-way trip to Wrocław.

**Comment by tudny** [comment]
We should change all `impl<T> ... where T: MatrixNumber` to `impl<T: MatrixNumber> ...`

**Comment by tudny** [comment]
The env should work in the editor now

**Comment by tudny** [comment]
@mgr0dzicki It's merging time everybody! https://www.youtube.com/watch?v=-XsYMHm64wM

**Review by mgr0dzicki — APPROVED** [review]
lgtm!

**Pull request merged**
